[package]
name = "ruddy-debug"
version = "0.1.0"
edition = "2024"

[dependencies]
ruddy = { path = ".." }
ruddy-cli = { package = "cli", path = "../cli" }
ruddy-js = { path = "../backend/js" }
indexmap = { version = "2", features = ["serde"] }
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = { version = "0.9", features = ["preserve_order"] }
