[package]
name = "ruddy-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
gix = { version = "0.85.0", default-features = false, features = ["sha1"] }
ruddy = { path = ".." }
ruddy-cli = { package = "cli", path = "../cli" }
ruddy-debug = { path = "../debug" }
ruddy-js = { path = "../backend/js" }
indexmap = "2"
regex = "1"
serde_json = "1"
tempfile = "3"
toml = "0.9"
