[package]
name = "ruddy-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
gix = { version = "0.85.0", default-features = false, features = ["sha1"] }
ruddy = { package = "ruddy-compiler", path = ".." }
ruddy-cli = { package = "ruddy", path = "../cli" }
ruddy-debug = { path = "../debug" }
ruddy-interp = { path = "../interp" }
indexmap = "2"
regex = "1"
serde_json = "1"
tempfile = "3"
toml = "0.9"
lsp-server = "0.10"
