//! Tests for the public JavaScript backend API and its generated ESM boundary.

use std::{fs, process::Command};

use ruddy::{
    artifact::{self, Artifact},
    backend::js::{self, Error},
    compile, inference, parse,
    symbol::{Bundle, Mint, Version},
    token,
    tracking::FileManager,
};

fn retag_numeric_global(
    artifact: &mut artifact::UncheckedArtifact,
    name: &str,
    rep: artifact::Rep,
) {
    let global = artifact
        .lir
        .globals
        .iter_mut()
        .find(|global| global.name.ends_with(&format!("::{name}")))
        .unwrap_or_else(|| panic!("no global named {name}"));
    for instr in &mut global.body.instrs {
        if instr.rep == artifact::Rep::Real {
            instr.rep = rep;
        }
        if let artifact::Op::Const(artifact::Literal::Real(bits)) = &mut instr.op {
            let value = f64::from_bits(*bits);
            instr.op = artifact::Op::Const(match rep {
                artifact::Rep::Nat => artifact::Literal::Natural(value as u64),
                artifact::Rep::Int => artifact::Literal::Integer(value as i64),
                _ => panic!("numeric retag requires an integer representation"),
            });
        }
    }
}

fn split_record_into_merge(artifact: &mut artifact::UncheckedArtifact, name: &str) {
    let global = artifact
        .lir
        .globals
        .iter_mut()
        .find(|global| global.name.ends_with(&format!("::{name}")))
        .unwrap_or_else(|| panic!("no global named {name}"));
    let combined = global.body.instrs.pop().expect("record constructor");
    let artifact::Op::Struct(fields) = &combined.op else {
        panic!("{name} does not end in a record")
    };
    let fields = fields.clone();
    assert_eq!(fields.len(), 2);
    let left_temp = combined.temp;
    let right_temp = left_temp + 1;
    let merged_temp = left_temp + 2;
    global.body.instrs.push(artifact::Instr {
        temp: left_temp,
        rep: artifact::Rep::Struct,
        op: artifact::Op::Struct(vec![fields[0].clone()]),
    });
    global.body.instrs.push(artifact::Instr {
        temp: right_temp,
        rep: artifact::Rep::Struct,
        op: artifact::Op::Struct(vec![fields[1].clone()]),
    });
    global.body.instrs.push(artifact::Instr {
        temp: merged_temp,
        rep: artifact::Rep::Struct,
        op: artifact::Op::Merge(vec![left_temp, right_temp]),
    });
    global.body.end = artifact::End::Ret(merged_temp);
}

fn retag_primitive_cases(
    artifact: &mut artifact::UncheckedArtifact,
    name: &str,
    rep: artifact::Rep,
) {
    let function = artifact
        .lir
        .functions
        .iter_mut()
        .find(|function| function.name.contains(name))
        .unwrap_or_else(|| panic!("no function named {name}"));
    function.params[0].rep = rep;
    let cases = function
        .body
        .instrs
        .iter_mut()
        .find_map(|instr| match &mut instr.op {
            artifact::Op::SwitchPrim { cases, .. } => Some(cases),
            _ => None,
        })
        .unwrap_or_else(|| panic!("{name} has no primitive switch"));
    for case in cases {
        let artifact::Literal::Real(bits) = case.value else {
            panic!("{name} has a non-real source case")
        };
        let value = f64::from_bits(bits);
        case.value = match rep {
            artifact::Rep::Nat => artifact::Literal::Natural(value as u64),
            artifact::Rep::Int => artifact::Literal::Integer(value as i64),
            _ => panic!("primitive retag requires an integer representation"),
        };
    }
}

fn compiled(source: &str) -> Artifact {
    let mut files = FileManager::new();
    let file = files.register_new_file("<javascript-test>".to_string(), source.to_string());
    let lexed = token::lex(source, file);
    assert!(lexed.errors.is_empty(), "{:#?}", lexed.errors);
    let parsed = parse::parse(lexed.tokens);
    assert!(parsed.errors.is_empty(), "{:#?}", parsed.errors);
    let bundle = Bundle::new("app", Version::new(1, 0, 0)).unwrap();
    compile::compile(Mint::new(bundle), parsed.stmts, inference::Trace::Off)
        .unwrap_or_else(|partial| panic!("{partial:#?}"))
        .artifact()
        .clone()
}

#[test]
fn public_generate_is_deterministic_and_emits_nested_esm_exports() {
    let artifact = compiled(
        "module Math =\n  let answer = 42n\n  let identity = fn x => x\nend\nlet ready = true\n",
    );
    let first = js::generate(&artifact).unwrap();
    let second = js::generate(&artifact).unwrap();

    assert_eq!(first, second);
    assert!(first.starts_with("// Generated by Ruddy.\n"), "{first}");
    assert!(first.contains("export {"), "{first}");
    assert!(
        first.contains("const $e0 = $namespace([[\"answer\","),
        "{first}"
    );
    assert!(first.contains("[\"identity\","), "{first}");
    assert!(first.contains(" as ready"), "{first}");
}

#[test]
fn generated_module_executes_values_functions_records_and_sums_in_node() {
    if Command::new("node").arg("--version").output().is_err() {
        return;
    }
    let artifact = compiled(
        "let answer = 42n\n\
         let apply = fn f => fn x => f x\n\
         let identity = fn n => n\n\
         let record = { value: answer }\n\
         let tagged = #Ready answer\n",
    );
    let module = js::generate(&artifact).unwrap();
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("app.mjs");
    fs::write(&path, module).unwrap();

    let probe = format!(
        "import * as app from {}; console.log(JSON.stringify([app.answer, app.apply(app.identity)(2), app.record.value, typeof app.tagged]));",
        serde_json::to_string(path.to_str().unwrap()).unwrap()
    );
    let output = Command::new("node")
        .args(["--input-type=module", "--eval", &probe])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout).unwrap().trim(),
        "[42,2,42,\"object\"]"
    );
}

#[test]
fn generated_module_erases_existential_packages_around_structs() {
    if Command::new("node").arg("--version").output().is_err() {
        return;
    }
    let artifact = compiled(
        "let build: Nat ->\n\
         { left when 'p: Nat, also when 'p: Nat, right when 'q: Nat }\n\
         where 'p != 'q = fn n => { left: n, also: n }\n\
         extern choose: Nat ->\n\
         { left when 'p: Nat, also when 'p: Nat, right when 'q: Nat }\n\
         where 'p != 'q = \"host.choose\"\n\
         let built = build 7n\n\
         let projected = (choose 8n).also\n\
         let matched = match choose 9n with\n\
         | { left, .. } => left\n\
         | { right, .. } => right\n\
         end\n",
    );
    let module = js::generate(&artifact).unwrap();
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("app.mjs");
    fs::write(&path, module).unwrap();

    let probe = format!(
        "globalThis.host = {{ choose: n => n === 9 ? {{ right: n }} : {{ left: n, also: n }} }}; const app = await import({}); console.log(JSON.stringify([app.built.left, app.projected, app.matched]));",
        serde_json::to_string(path.to_str().unwrap()).unwrap()
    );
    let output = Command::new("node")
        .args(["--input-type=module", "--eval", &probe])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap().trim(), "[7,8,9]");
}

#[test]
fn generated_module_executes_tuple_values_projections_and_patterns() {
    if Command::new("node").arg("--version").output().is_err() {
        return;
    }
    let artifact = compiled(
        "let pair : { 0: Nat, 1: String } = { 000: 42n, 1: \"answer\" }\n\
         let singleton = (true,)\n\
         let first = pair.0\n\
         let second = pair.1\n\
         let swap : (Nat, String) -> (String, Nat) = fn value => match value with \
         | { 0: number, 1: text } => (text, number) end\n",
    );
    let module = js::generate(&artifact).unwrap();
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("tuples.mjs");
    fs::write(&path, module).unwrap();

    let probe = format!(
        "const app = await import({}); const swapped = app.swap(app.pair); console.log(JSON.stringify([app.pair[0], app.pair[1], app.singleton[0], app.first, app.second, swapped[0], swapped[1]]));",
        serde_json::to_string(path.to_str().unwrap()).unwrap()
    );
    let output = Command::new("node")
        .args(["--input-type=module", "--eval", &probe])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout).unwrap().trim(),
        "[42,\"answer\",true,42,\"answer\",\"answer\",42]"
    );
}

#[test]
fn generated_runtime_preserves_arithmetic_switch_record_effect_and_literal_semantics() {
    if Command::new("node").arg("--version").output().is_err() {
        return;
    }
    // Arithmetic operators currently surface as Real in source inference. Retag the
    // three focused initializers and two primitive cases to exercise the backend's
    // Nat/Int representations exactly as linked artifact LIR records them.
    let mut artifact = compiled(
        "let nat_sub = 2.0 - 5.0\n\
         let int_div = -7.0 / 2.0\n\
         let int_negative_zero = 0.0 / -1.0\n\
         let real_div = 1.0 / 0.0\n\
         let real_literal = 1.5\n\
         let classify_nat = fn n => match n with | 0.0 => \"zero\" | 1.0 => \"one\" | _ => \"other\" end\n\
         let classify_int = fn n => match n with | 0.0 => \"zero\" | _ => \"other\" end\n\
         let classify_real = fn n => match n with | 0.0 => \"positive zero\" | _ => \"other\" end\n\
         let unpack = fn value => match value with | #Value n => n | #Empty => 0n | _ => 99n end\n\
         let payload = unpack (#Value 8n)\n\
         let tag_fallback = unpack #Other\n\
         let shape = fn value => match value with | { x } => 1n | { x, .. } => 2n | _ => 3n end\n\
         let merged = { left: 1n, right: 2n }\n\
         effect Bump = Real -> Real\n\
         let bump = fn n => handle !Bump n with | !Bump value => value + 1.0 end\n\
         effect Read = { get: () -> Nat }\n\
         let read = fn _ => handle !Read.get () with | !Read.get _ => 42n end\n\
         effect Plus = { apply: Real -> Real }\n\
         effect Times = { apply: Real -> Real }\n\
         let calculate : Real -> Real + !Plus + !Times = fn n => do let x = !Plus.apply n return !Times.apply x end\n\
         let calculated = fn n => handle (handle calculate n with | !Plus.apply value => value + 1.0 end) with | !Times.apply value => value * 2.0 end\n\
         effect Ask 'a = { get: () -> 'a }\n\
         let asked = fn n => handle do let x = !Ask.get () return x + n end with | !Ask.get _ => 1.0 end\n",
    )
    .to_unchecked();
    retag_numeric_global(&mut artifact, "nat_sub", artifact::Rep::Nat);
    retag_numeric_global(&mut artifact, "int_div", artifact::Rep::Int);
    retag_numeric_global(&mut artifact, "int_negative_zero", artifact::Rep::Int);
    retag_primitive_cases(&mut artifact, "classify_nat", artifact::Rep::Nat);
    retag_primitive_cases(&mut artifact, "classify_int", artifact::Rep::Int);
    split_record_into_merge(&mut artifact, "merged");
    let artifact = artifact
        .validate()
        .expect("the retagged artifact validates");
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("semantics.mjs");
    let module = js::generate(&artifact).unwrap();
    assert!(
        module.contains("Object.assign(Object.create(null)"),
        "artifact fixture did not exercise record merging"
    );
    fs::write(&path, module).unwrap();
    let probe = format!(
        "const app = await import({}); const values = [app.nat_sub, app.int_div, Object.is(app.int_negative_zero, -0), Number.isFinite(app.real_div), app.real_literal, app.classify_nat(-0), app.classify_nat(7), app.classify_int(app.int_negative_zero), app.classify_real(0), app.classify_real(-0), app.payload, app.tag_fallback, app.shape({{x: 4}}), app.shape({{x: 4, y: 5}}), app.shape({{y: 5}}), app.merged.left + app.merged.right, app.bump(4), app.read(null), app.calculated(4), app.asked(4)]; console.log(JSON.stringify(values));",
        serde_json::to_string(path.to_str().unwrap()).unwrap()
    );
    let output = Command::new("node")
        .args(["--input-type=module", "--eval", &probe])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout).unwrap().trim(),
        "[0,-3,true,false,1.5,\"zero\",\"other\",\"zero\",\"positive zero\",\"other\",8,99,1,2,3,3,5,42,10,5]"
    );
}

#[test]
fn generation_rejects_unlinked_and_internally_inconsistent_artifacts() {
    let mut unlinked = compiled("let value = 1n").to_unchecked();
    unlinked.header.dependencies.push(artifact::Dependency {
        name: "dep".to_string(),
        version: "1.0.0".to_string(),
    });
    let unlinked = unlinked.validate().expect("an unlinked artifact validates");
    assert_eq!(js::generate(&unlinked), Err(Error::Unlinked));
    assert_eq!(
        Error::Unlinked.to_string(),
        "the JavaScript backend requires a linked artifact"
    );

    let mut missing_public = compiled("let value = 1n").to_unchecked();
    missing_public.header.values[0].name = "app@1.0.0::missing".to_string();
    let missing_public = missing_public
        .validate()
        .expect("a missing public value validates");
    assert_eq!(
        js::generate(&missing_public),
        Err(Error::UnresolvedPublicValue(
            "app@1.0.0::missing".to_string()
        ))
    );

    let mut bad_global = compiled("let value = 1n").to_unchecked();
    bad_global.lir.globals[0].body.instrs[0].op = artifact::Op::Global {
        target: "unknown@1.0.0::value".to_string(),
    };
    let bad_global = bad_global
        .validate()
        .expect("an unknown global reference validates");
    assert_eq!(
        js::generate(&bad_global),
        Err(Error::InvalidGlobalReference(
            "unknown@1.0.0::value".to_string()
        ))
    );

    let mut bad_function = compiled("let identity = fn x => x").to_unchecked();
    let closure = bad_function.lir.globals[0]
        .body
        .instrs
        .iter_mut()
        .find(|instr| matches!(instr.op, artifact::Op::Closure { .. }))
        .unwrap();
    closure.op = artifact::Op::Closure {
        func: u64::MAX,
        captures: Vec::new(),
    };
    // TODO: `Error::InvalidFunctionReference` is no longer reachable through
    // the public API. A dangling function index never becomes an `Artifact`:
    // `validate` rejects it and `recover` discards the executable content, so
    // the backend cannot be handed one. The boundary is asserted instead.
    let error = bad_function
        .clone()
        .validate()
        .expect_err("a dangling function index is rejected");
    assert!(
        error.message().contains("outside its function table"),
        "{error}"
    );
    let (recovered, facts) = bad_function.recover();
    assert!(
        matches!(
            facts.as_slice(),
            [artifact::RecoveryFact::ExecutableDiscarded { .. }]
        ),
        "{facts:#?}"
    );
    assert!(recovered.lir().functions.is_empty());
    assert!(recovered.lir().globals.is_empty());

    let mut conflicting = compiled("let first = 1n\nlet second = 2n").to_unchecked();
    conflicting.header.values[0].name = "app@1.0.0::path".to_string();
    conflicting.lir.globals[0].name = "app@1.0.0::path".to_string();
    conflicting.header.values[1].name = "app@1.0.0::path::child".to_string();
    conflicting.lir.globals[1].name = "app@1.0.0::path::child".to_string();
    let conflicting = conflicting
        .validate()
        .expect("a conflicting export tree validates");
    assert_eq!(
        js::generate(&conflicting),
        Err(Error::ExportTreeConflict("path".to_string()))
    );
}

#[test]
fn generated_extern_expressions_execute_once_and_require_explicit_receiver_binding() {
    if Command::new("node").arg("--version").output().is_err() {
        return;
    }
    let artifact = compiled(
        "extern next : Nat -> Nat = \"(++globalThis.initializations, globalThis.host.next.bind(globalThis.host))\"\n\
         extern base : Nat = \"globalThis.host.base\"\n\
         extern add_base : Nat -> Nat = \"n => n + globalThis.host.base\"\n",
    );
    let module = js::generate(&artifact).unwrap();
    assert!(
        module
            .contains("(++globalThis.initializations, globalThis.host.next.bind(globalThis.host))"),
        "extern contents were not emitted as JavaScript code: {module}"
    );
    assert!(!module.contains("const $extern"), "{module}");

    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("extern.mjs");
    fs::write(&path, module).unwrap();
    let probe = format!(
        "globalThis.initializations = 0; globalThis.host = {{ base: 40, next(n) {{ return this.base + n; }} }}; const app = await import({}); console.log(JSON.stringify([app.next(2), app.base, app.add_base(2), globalThis.initializations]));",
        serde_json::to_string(path.to_str().unwrap()).unwrap()
    );
    let output = Command::new("node")
        .args(["--input-type=module", "--eval", &probe])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout).unwrap().trim(),
        "[42,40,42,1]"
    );
}

#[test]
fn invalid_empty_and_structurally_breaking_extern_expressions_are_rejected() {
    let mut artifact = compiled("extern host : Nat = \"0\"\n").to_unchecked();
    for target in [
        "(",
        "",
        "0); export const injected = 1; (2",
        "0); import 'injected'; (2",
        "0); globalThis.injected = true; (2",
    ] {
        artifact.lir.externs[0].target = target.to_string();
        let artifact = artifact
            .clone()
            .validate()
            .expect("an extern target string validates");
        let error = js::generate(&artifact).unwrap_err();
        assert!(
            matches!(error, Error::InvalidJavaScript(ref diagnostic) if !diagnostic.is_empty()),
            "accepted `{target}`: {error}"
        );
        assert!(
            error
                .to_string()
                .starts_with("generated JavaScript is invalid: "),
            "{error}"
        );
        let _: &dyn std::error::Error = &error;
    }
}

#[test]
fn trailing_line_comments_in_extern_expressions_do_not_consume_the_initializer() {
    let artifact = compiled("extern host : Nat = \"globalThis.host // trailing comment\"\n");
    let module = js::generate(&artifact).unwrap();
    assert!(
        module.contains("globalThis.host // trailing comment\n);"),
        "{module}"
    );
}
