[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[lib]
name = "ruddy_cli"

[[bin]]
name = "ruddy"
path = "src/main.rs"

[dependencies]
boa_engine = "0.22"
boa_runtime = { version = "0.22", features = ["all", "process"] }
clap = { version = "4", features = ["derive"] }
gix = { version = "0.85.0", default-features = false, features = ["sha1", "blocking-http-transport-reqwest-rust-tls", "worktree-mutation", "revision"] }
fs2 = "0.4.3"
indexmap = { version = "2", features = ["serde"] }
ruddy = { path = ".." }
ruddy-js = { path = "../backend/js" }
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9", features = ["preserve_order"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
