[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[lib]
name = "ruddy_cli"

[[bin]]
name = "ruddy"
path = "src/main.rs"

[dependencies]
gix = { version = "0.87.1", default-features = false, features = ["sha1"] }
indexmap = { version = "2", features = ["serde"] }
ruddy = { path = ".." }
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9", features = ["preserve_order"] }
