extern len : ['a] -> Nat = "$arrayLen"
extern get : ['a] -> Nat -> Option 'a = "$arrayGet"
extern set : ['a] -> Nat -> 'a -> Option ['a] = "$arraySet"
extern push : ['a] -> 'a -> ['a] = "$arrayPush"
extern concat : ['a] -> ['a] -> ['a] = "$arrayConcat"
extern slice : ['a] -> Nat -> Nat -> Option ['a] = "$arraySlice"
extern prepend : ['a] -> 'a -> ['a] = "$arrayPrepend"
extern pop : ['a] -> Option ('a, ['a]) = "$arrayPop"
